name: Release library

on:
    release:
        types: [created]

jobs:
    ci_release:
        uses: dsi-hug/actions/.github/workflows/action.yml@v3
        secrets:
            NPM_TOKEN: ${{ secrets.DSI_HUG_NPM_TOKEN }}
        with:
            working-directory: .
            lint: true
            test: false
            build: true
            release: true
